version: '3.9'

services:
  db:
    build:
      context: ./db
    container_name: sqlite_db
    volumes:
      - db_data:/data/db
    networks:
      - app_network

  app:
    build:
      context: ./app
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - db_data:/data/db
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
